package container_test

import (
	"io"
	"strings"
	"testing"

	. "github.com/mmdemirbas/logmerge/internal/container"
	"github.com/mmdemirbas/logmerge/internal/testutil"
)

func TestRingBuffer(t *testing.T) {
	t.Run("NewRingBuffer", func(t *testing.T) {
		t.Run("-1-cap", func(t *testing.T) {
			r := NewRingBuffer(-1)
			testutil.AssertEquals(t, nil, r)
		})
		t.Run("0-cap", func(t *testing.T) {
			r := NewRingBuffer(0)
			testutil.AssertEquals(t, nil, r)
		})
		t.Run("1-cap", func(t *testing.T) {
			r := NewRingBuffer(1)
			testutil.AssertNotEquals(t, nil, r)
		})
	})

	t.Run("IsEmpty-IsFull-Len", func(t *testing.T) {
		t.Run("new buffer", func(t *testing.T) {
			r := NewRingBuffer(3)
			testutil.AssertEquals(t, "", r.String())
			testutil.AssertEquals(t, true, r.IsEmpty())
			testutil.AssertEquals(t, false, r.IsFull())
			testutil.AssertEquals(t, 0, r.Len())
		})

		t.Run("half-full buffer", func(t *testing.T) {
			r := NewRingBuffer(3)
			r.Write('a')
			testutil.AssertEquals(t, "a", r.String())
			testutil.AssertEquals(t, false, r.IsEmpty())
			testutil.AssertEquals(t, false, r.IsFull())
			testutil.AssertEquals(t, 1, r.Len())
		})

		t.Run("full buffer", func(t *testing.T) {
			r := NewRingBuffer(3)
			r.Write('a')
			r.Write('b')
			r.Write('c')
			testutil.AssertEquals(t, "abc", r.String())
			testutil.AssertEquals(t, false, r.IsEmpty())
			testutil.AssertEquals(t, true, r.IsFull())
			testutil.AssertEquals(t, 3, r.Len())
		})

		t.Run("empty buffer after read", func(t *testing.T) {
			r := NewRingBuffer(3)
			r.Write('a')
			r.Read()
			testutil.AssertEquals(t, "", r.String())
			testutil.AssertEquals(t, true, r.IsEmpty())
			testutil.AssertEquals(t, false, r.IsFull())
			testutil.AssertEquals(t, 0, r.Len())
		})

		t.Run("half-full buffer after read", func(t *testing.T) {
			r := NewRingBuffer(3)
			r.Write('a')
			r.Write('b')
			r.Read()
			r.Write('c')
			testutil.AssertEquals(t, "bc", r.String())
			testutil.AssertEquals(t, false, r.IsEmpty())
			testutil.AssertEquals(t, false, r.IsFull())
			testutil.AssertEquals(t, 2, r.Len())
		})

		t.Run("full buffer after read", func(t *testing.T) {
			r := NewRingBuffer(3)
			r.Write('a')
			r.Write('b')
			r.Write('c')
			r.Read()
			r.Write('d')
			testutil.AssertEquals(t, "bcd", r.String())
			testutil.AssertEquals(t, false, r.IsEmpty())
			testutil.AssertEquals(t, true, r.IsFull())
			testutil.AssertEquals(t, 3, r.Len())
		})
	})

	t.Run("Peek-Skip", func(t *testing.T) {
		r := NewRingBuffer(3)
		r.Write('a')
		r.Write('b')
		testutil.AssertEquals(t, "ab", r.String())

		testutil.AssertEquals(t, byte('a'), r.Peek(0))
		testutil.AssertEquals(t, byte('b'), r.Peek(1))
		testutil.AssertEquals(t, "ab", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 2, r.Len())

		r.Write('c')
		testutil.AssertEquals(t, "abc", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, true, r.IsFull())
		testutil.AssertEquals(t, 3, r.Len())

		testutil.AssertEquals(t, byte('a'), r.Peek(0))
		testutil.AssertEquals(t, byte('b'), r.Peek(1))
		testutil.AssertEquals(t, byte('c'), r.Peek(2))
		testutil.AssertEquals(t, "abc", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, true, r.IsFull())
		testutil.AssertEquals(t, 3, r.Len())

		r.Skip(1)
		testutil.AssertEquals(t, "bc", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 2, r.Len())

		testutil.AssertEquals(t, byte('b'), r.Peek(0))
		testutil.AssertEquals(t, byte('c'), r.Peek(1))
		testutil.AssertEquals(t, "bc", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 2, r.Len())

		r.Skip(1)
		testutil.AssertEquals(t, "c", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 1, r.Len())

		testutil.AssertEquals(t, byte('c'), r.Peek(0))
		testutil.AssertEquals(t, "c", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 1, r.Len())

		r.Skip(1)
		testutil.AssertEquals(t, "", r.String())
		testutil.AssertEquals(t, true, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 0, r.Len())

		r.Write('d')
		testutil.AssertEquals(t, "d", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 1, r.Len())

		testutil.AssertEquals(t, byte('d'), r.Peek(0))
		testutil.AssertEquals(t, "d", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 1, r.Len())

		r.Skip(1)
		testutil.AssertEquals(t, "", r.String())
		testutil.AssertEquals(t, true, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 0, r.Len())
	})

	t.Run("Read-Write", func(t *testing.T) {
		r := NewRingBuffer(3)
		r.Write('a')
		r.Write('b')
		r.Write('c')
		testutil.AssertEquals(t, "abc", r.String())

		testutil.AssertEquals(t, byte('a'), r.Read())
		testutil.AssertEquals(t, "bc", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 2, r.Len())

		testutil.AssertEquals(t, byte('b'), r.Read())
		testutil.AssertEquals(t, "c", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 1, r.Len())

		testutil.AssertEquals(t, byte('c'), r.Read())
		testutil.AssertEquals(t, "", r.String())
		testutil.AssertEquals(t, true, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 0, r.Len())

		r.Write('d')
		testutil.AssertEquals(t, "d", r.String())
		testutil.AssertEquals(t, false, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 1, r.Len())

		testutil.AssertEquals(t, byte('d'), r.Read())
		testutil.AssertEquals(t, "", r.String())
		testutil.AssertEquals(t, true, r.IsEmpty())
		testutil.AssertEquals(t, false, r.IsFull())
		testutil.AssertEquals(t, 0, r.Len())
	})

	t.Run("Fill", func(t *testing.T) {
		t.Run("new buffer", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				n, err := r.Fill(strings.NewReader(""))
				testutil.AssertEquals(t, "", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, io.EOF, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				n, err := r.Fill(strings.NewReader("ab"))
				testutil.AssertEquals(t, "ab", r.String())
				testutil.AssertEquals(t, 2, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				n, err := r.Fill(strings.NewReader("abc"))
				testutil.AssertEquals(t, "abc", r.String())
				testutil.AssertEquals(t, 3, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				n, err := r.Fill(strings.NewReader("abcdef"))
				testutil.AssertEquals(t, "abc", r.String())
				testutil.AssertEquals(t, 3, n)
				testutil.AssertEquals(t, nil, err)
			})
		})
		t.Run("half-full buffer", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				n, err := r.Fill(strings.NewReader(""))
				testutil.AssertEquals(t, "x", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, io.EOF, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				n, err := r.Fill(strings.NewReader("ab"))
				testutil.AssertEquals(t, "xab", r.String())
				testutil.AssertEquals(t, 2, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				n, err := r.Fill(strings.NewReader("abc"))
				testutil.AssertEquals(t, "xab", r.String())
				testutil.AssertEquals(t, 2, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				n, err := r.Fill(strings.NewReader("abcdef"))
				testutil.AssertEquals(t, "xab", r.String())
				testutil.AssertEquals(t, 2, n)
				testutil.AssertEquals(t, nil, err)
			})
		})
		t.Run("full buffer", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				n, err := r.Fill(strings.NewReader(""))
				testutil.AssertEquals(t, "xyz", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				n, err := r.Fill(strings.NewReader("ab"))
				testutil.AssertEquals(t, "xyz", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				n, err := r.Fill(strings.NewReader("abc"))
				testutil.AssertEquals(t, "xyz", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				n, err := r.Fill(strings.NewReader("abcdef"))
				testutil.AssertEquals(t, "xyz", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, nil, err)
			})
		})
		t.Run("full buffer after read", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				n, err := r.Fill(strings.NewReader(""))
				testutil.AssertEquals(t, "yzt", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				n, err := r.Fill(strings.NewReader("ab"))
				testutil.AssertEquals(t, "yzt", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				n, err := r.Fill(strings.NewReader("abc"))
				testutil.AssertEquals(t, "yzt", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				n, err := r.Fill(strings.NewReader("abcdef"))
				testutil.AssertEquals(t, "yzt", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, nil, err)
			})
		})
		t.Run("half-full buffer after read", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				n, err := r.Fill(strings.NewReader(""))
				testutil.AssertEquals(t, "t", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, io.EOF, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				n, err := r.Fill(strings.NewReader("ab"))
				testutil.AssertEquals(t, "tab", r.String())
				testutil.AssertEquals(t, 2, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				n, err := r.Fill(strings.NewReader("abc"))
				testutil.AssertEquals(t, "tab", r.String())
				testutil.AssertEquals(t, 2, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				n, err := r.Fill(strings.NewReader("abcdef"))
				testutil.AssertEquals(t, "tab", r.String())
				testutil.AssertEquals(t, 2, n)
				testutil.AssertEquals(t, nil, err)
			})
		})
		t.Run("empty buffer after read", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				r.Read()
				n, err := r.Fill(strings.NewReader(""))
				testutil.AssertEquals(t, "", r.String())
				testutil.AssertEquals(t, 0, n)
				testutil.AssertEquals(t, io.EOF, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				r.Read()
				n, err := r.Fill(strings.NewReader("ab"))
				testutil.AssertEquals(t, "ab", r.String())
				testutil.AssertEquals(t, 2, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				r.Read()
				n, err := r.Fill(strings.NewReader("abc"))
				testutil.AssertEquals(t, "abc", r.String())
				testutil.AssertEquals(t, 3, n)
				testutil.AssertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				r.Read()
				n, err := r.Fill(strings.NewReader("abcdef"))
				testutil.AssertEquals(t, "abc", r.String())
				testutil.AssertEquals(t, 3, n)
				testutil.AssertEquals(t, nil, err)
			})
		})
	})

	t.Run("EOL Parsing", func(t *testing.T) {
		t.Run("Empty Buffer", func(t *testing.T) {
			r := NewRingBuffer(5)
			latestCR := false
			slice, eol := r.PeekNextLineSlice(&latestCR)
			testutil.AssertEquals(t, []byte(nil), slice)
			testutil.AssertEquals(t, None, eol)

			n, eolSkip := r.SkipNextLineSlice(&latestCR)
			testutil.AssertEquals(t, 0, n)
			testutil.AssertEquals(t, None, eolSkip)
		})

		t.Run("No EOL", func(t *testing.T) {
			r := NewRingBuffer(5)
			r.Write('a')
			r.Write('b')
			latestCR := false
			slice, eol := r.PeekNextLineSlice(&latestCR)
			testutil.AssertEquals(t, []byte("ab"), slice)
			testutil.AssertEquals(t, None, eol)

			n, eolSkip := r.SkipNextLineSlice(&latestCR)
			testutil.AssertEquals(t, 2, n)
			testutil.AssertEquals(t, None, eolSkip)
			testutil.AssertEquals(t, 0, r.Len())
		})

		t.Run("LF only", func(t *testing.T) {
			r := NewRingBuffer(5)
			r.Write('a')
			r.Write('\n')
			r.Write('b')
			latestCR := false
			slice, eol := r.PeekNextLineSlice(&latestCR)
			testutil.AssertEquals(t, []byte("a\n"), slice)
			testutil.AssertEquals(t, LF, eol)

			n, eolSkip := r.SkipNextLineSlice(&latestCR)
			testutil.AssertEquals(t, 2, n)
			testutil.AssertEquals(t, LF, eolSkip)
			testutil.AssertEquals(t, 1, r.Len())
		})

		t.Run("CR only", func(t *testing.T) {
			r := NewRingBuffer(5)
			r.Write('a')
			r.Write('\r')
			r.Write('b')
			latestCR := false
			slice, eol := r.PeekNextLineSlice(&latestCR)
			testutil.AssertEquals(t, []byte("a\r"), slice)
			testutil.AssertEquals(t, CR, eol)

			n, eolSkip := r.SkipNextLineSlice(&latestCR)
			testutil.AssertEquals(t, 2, n)
			testutil.AssertEquals(t, CR, eolSkip)
			testutil.AssertEquals(t, 1, r.Len())
		})

		t.Run("CRLF", func(t *testing.T) {
			r := NewRingBuffer(5)
			r.Write('a')
			r.Write('\r')
			r.Write('\n')
			latestCR := false
			slice, eol := r.PeekNextLineSlice(&latestCR)
			testutil.AssertEquals(t, []byte("a\r\n"), slice)
			testutil.AssertEquals(t, CRLF, eol)
		})

		t.Run("Split CRLF", func(t *testing.T) {
			r := NewRingBuffer(5)
			latestCR := true
			r.Write('\n')
			slice, eol := r.PeekNextLineSlice(&latestCR)
			testutil.AssertEquals(t, []byte("\n"), slice)
			testutil.AssertEquals(t, CRLF, eol)
			testutil.AssertEquals(t, false, latestCR)
		})
	})

	t.Run("PeekSlice", func(t *testing.T) {
		r := NewRingBuffer(5)
		r.Write('a')
		r.Write('b')
		r.Write('c')

		buf := make([]byte, 5)
		res := r.PeekSlice(buf)
		testutil.AssertEquals(t, []byte("abc"), res)
		testutil.AssertEquals(t, 3, r.Len())
	})
}
