package main_test

import (
	. "github.com/mmdemirbas/logmerge"
	"io"
	"strings"
	"testing"
)

func TestNewRingBuffer(t *testing.T) {
	t.Run("NewRingBuffer", func(t *testing.T) {
		t.Run("-1-cap", func(t *testing.T) {
			r := NewRingBuffer(-1)
			assertEquals(t, nil, r)
		})
		t.Run("0-cap", func(t *testing.T) {
			r := NewRingBuffer(0)
			assertEquals(t, nil, r)
		})
		t.Run("1-cap", func(t *testing.T) {
			r := NewRingBuffer(1)
			assertNotEquals(t, nil, r)
		})
	})

	t.Run("IsEmpty-IsFull-Len", func(t *testing.T) {
		t.Run("new buffer", func(t *testing.T) {
			r := NewRingBuffer(3)
			assertEquals(t, "", r.String())
			assertEquals(t, true, r.IsEmpty())
			assertEquals(t, false, r.IsFull())
			assertEquals(t, 0, r.Len())
		})

		t.Run("half-full buffer", func(t *testing.T) {
			r := NewRingBuffer(3)
			r.Write('a')
			assertEquals(t, "a", r.String())
			assertEquals(t, false, r.IsEmpty())
			assertEquals(t, false, r.IsFull())
			assertEquals(t, 1, r.Len())
		})

		t.Run("full buffer", func(t *testing.T) {
			r := NewRingBuffer(3)
			r.Write('a')
			r.Write('b')
			r.Write('c')
			assertEquals(t, "abc", r.String())
			assertEquals(t, false, r.IsEmpty())
			assertEquals(t, true, r.IsFull())
			assertEquals(t, 3, r.Len())
		})

		t.Run("empty buffer after read", func(t *testing.T) {
			r := NewRingBuffer(3)
			r.Write('a')
			r.Read()
			assertEquals(t, "", r.String())
			assertEquals(t, true, r.IsEmpty())
			assertEquals(t, false, r.IsFull())
			assertEquals(t, 0, r.Len())
		})

		t.Run("half-full buffer after read", func(t *testing.T) {
			r := NewRingBuffer(3)
			r.Write('a')
			r.Write('b')
			r.Read()
			r.Write('c')
			assertEquals(t, "bc", r.String())
			assertEquals(t, false, r.IsEmpty())
			assertEquals(t, false, r.IsFull())
			assertEquals(t, 2, r.Len())
		})

		t.Run("full buffer after read", func(t *testing.T) {
			r := NewRingBuffer(3)
			r.Write('a')
			r.Write('b')
			r.Write('c')
			r.Read()
			r.Write('d')
			assertEquals(t, "bcd", r.String())
			assertEquals(t, false, r.IsEmpty())
			assertEquals(t, true, r.IsFull())
			assertEquals(t, 3, r.Len())
		})
	})

	t.Run("Peek-Next", func(t *testing.T) {
		r := NewRingBuffer(3)
		r.Write('a')
		r.Write('b')
		assertEquals(t, "ab", r.String())

		assertEquals(t, byte('a'), r.Peek())
		assertEquals(t, "ab", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 2, r.Len())

		r.Write('c')
		assertEquals(t, "abc", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, true, r.IsFull())
		assertEquals(t, 3, r.Len())

		assertEquals(t, byte('a'), r.Peek())
		assertEquals(t, "abc", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, true, r.IsFull())
		assertEquals(t, 3, r.Len())

		r.Next()
		assertEquals(t, "bc", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 2, r.Len())

		assertEquals(t, byte('b'), r.Peek())
		assertEquals(t, "bc", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 2, r.Len())

		r.Next()
		assertEquals(t, "c", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 1, r.Len())

		assertEquals(t, byte('c'), r.Peek())
		assertEquals(t, "c", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 1, r.Len())

		r.Next()
		assertEquals(t, "", r.String())
		assertEquals(t, true, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 0, r.Len())

		r.Write('d')
		assertEquals(t, "d", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 1, r.Len())

		assertEquals(t, byte('d'), r.Peek())
		assertEquals(t, "d", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 1, r.Len())

		r.Next()
		assertEquals(t, "", r.String())
		assertEquals(t, true, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 0, r.Len())
	})

	t.Run("Read-Write", func(t *testing.T) {
		r := NewRingBuffer(3)
		r.Write('a')
		r.Write('b')
		r.Write('c')
		assertEquals(t, "abc", r.String())

		assertEquals(t, byte('a'), r.Read())
		assertEquals(t, "bc", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 2, r.Len())

		assertEquals(t, byte('b'), r.Read())
		assertEquals(t, "c", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 1, r.Len())

		assertEquals(t, byte('c'), r.Read())
		assertEquals(t, "", r.String())
		assertEquals(t, true, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 0, r.Len())

		r.Write('d')
		assertEquals(t, "d", r.String())
		assertEquals(t, false, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 1, r.Len())

		assertEquals(t, byte('d'), r.Read())
		assertEquals(t, "", r.String())
		assertEquals(t, true, r.IsEmpty())
		assertEquals(t, false, r.IsFull())
		assertEquals(t, 0, r.Len())
	})

	t.Run("Fill", func(t *testing.T) {
		t.Run("new buffer", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				err := r.Fill(strings.NewReader(""))
				assertEquals(t, "", r.String())
				assertEquals(t, io.EOF, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				err := r.Fill(strings.NewReader("ab"))
				assertEquals(t, "ab", r.String())
				assertEquals(t, io.EOF, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				err := r.Fill(strings.NewReader("abc"))
				assertEquals(t, "abc", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				err := r.Fill(strings.NewReader("abcdef"))
				assertEquals(t, "abc", r.String())
				assertEquals(t, nil, err)
			})
		})
		t.Run("half-full buffer", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				err := r.Fill(strings.NewReader(""))
				assertEquals(t, "x", r.String())
				assertEquals(t, io.EOF, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				err := r.Fill(strings.NewReader("ab"))
				assertEquals(t, "xab", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				err := r.Fill(strings.NewReader("abc"))
				assertEquals(t, "xab", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				err := r.Fill(strings.NewReader("abcdef"))
				assertEquals(t, "xab", r.String())
				assertEquals(t, nil, err)
			})
		})
		t.Run("full buffer", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				err := r.Fill(strings.NewReader(""))
				assertEquals(t, "xyz", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				err := r.Fill(strings.NewReader("ab"))
				assertEquals(t, "xyz", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				err := r.Fill(strings.NewReader("abc"))
				assertEquals(t, "xyz", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				err := r.Fill(strings.NewReader("abcdef"))
				assertEquals(t, "xyz", r.String())
				assertEquals(t, nil, err)
			})
		})
		t.Run("full buffer after read", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				err := r.Fill(strings.NewReader(""))
				assertEquals(t, "yzt", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				err := r.Fill(strings.NewReader("ab"))
				assertEquals(t, "yzt", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				err := r.Fill(strings.NewReader("abc"))
				assertEquals(t, "yzt", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				err := r.Fill(strings.NewReader("abcdef"))
				assertEquals(t, "yzt", r.String())
				assertEquals(t, nil, err)
			})
		})
		t.Run("half-full buffer after read", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				err := r.Fill(strings.NewReader(""))
				assertEquals(t, "t", r.String())
				assertEquals(t, io.EOF, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				err := r.Fill(strings.NewReader("ab"))
				assertEquals(t, "tab", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				err := r.Fill(strings.NewReader("abc"))
				assertEquals(t, "tab", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				err := r.Fill(strings.NewReader("abcdef"))
				assertEquals(t, "tab", r.String())
				assertEquals(t, nil, err)
			})
		})
		t.Run("empty buffer after read", func(t *testing.T) {
			t.Run("empty reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				r.Read()
				err := r.Fill(strings.NewReader(""))
				assertEquals(t, "", r.String())
				assertEquals(t, io.EOF, err)
			})
			t.Run("shorter reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				r.Read()
				err := r.Fill(strings.NewReader("ab"))
				assertEquals(t, "ab", r.String())
				assertEquals(t, io.EOF, err)
			})
			t.Run("equal reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				r.Read()
				err := r.Fill(strings.NewReader("abc"))
				assertEquals(t, "abc", r.String())
				assertEquals(t, nil, err)
			})
			t.Run("longer reader", func(t *testing.T) {
				r := NewRingBuffer(3)
				r.Write('x')
				r.Write('y')
				r.Write('z')
				r.Read()
				r.Write('t')
				r.Read()
				r.Read()
				r.Read()
				err := r.Fill(strings.NewReader("abcdef"))
				assertEquals(t, "abc", r.String())
				assertEquals(t, nil, err)
			})
		})
	})
}
