OutputFile: "/Users/md/dev/mmdemirbas/logmerge/out/output.log"
LogFile: "/Users/md/dev/mmdemirbas/logmerge/log/129-0501-metrics.err"

ProfilingEnabled: false

ListFilesConfig:
#  InputPath: "/Users/md/code/spark-kit/memartscc-token-renewal/remote-test/log/" # 8184
  InputPath: "/Users/md/code/spark-kit/memartscc-token-renewal/remote-test/log/application_1734940586637_0046-short-success" # 0501
#  InputPath: "/Users/md/code/spark-kit/memartscc-token-renewal/remote-test/log/application_1736261418288_0021" # 0320
#  InputPath: "/Users/md/code/spark-kit/memartscc-token-renewal/remote-test/log/application_1736999506338_0001-ANALYSIS" # 0070

  ExcludedStrictSuffixes: [ ".zip", ".tar", ".gz", ".rar", ".7z", ".tgz", ".bz2", ".tbz2", ".xz", ".txz" ]
  IncludedStrictSuffixes: [ ]
  ExcludedLenientSuffixes: [ ]
  IncludedLenientSuffixes: [ ".log", ".err", ".error", ".warn", ".warning", ".info", ".out", ".debug", ".trace" ]

  FileAliases:
    "172.16.0.240/memartscc/cc-worker/ccworker.INFO.20250115-172150.3239354": "cc"
    "172.16.0.240/memartscc/cc-worker/ccworker.INFO": "cc"
    "172.16.0.240/memartscc/cc-worker/ccworker.WARNING.20250115-172623.3239354": "cc"
    "172.16.0.240/memartscc/cc-worker/ccworker.WARNING": "cc"
    "172.16.0.240/memartscc/cc-worker/ccworker.ERROR.20250115-172623.3239354": "cc"
    "172.16.0.240/memartscc/cc-worker/ccworker.ERROR": "cc"
    "172.16.0.240/memartscc/check-worker-instance.log": "cc"
    "172.16.0.240/memartscc/cc-sidecar/cc-sidecar.log": "cc-sidecar"
    "172.16.0.240/memartscc/check-sidecar-instance.log": "cc-sidecar"
    "172.16.0.240/memartscc/cc-sidecar/cc-sidecar-bg-task.log": "cc-sidecar"
    "172.16.0.240/memartscc/checkServiceHealthCheck.log": "cc-health"
    "172.16.0.240/yarn/nm/yarn-nodemanager-period-check.log": "yarn-nodemanager-period-check"
    "172.16.0.240/yarn/nm/nodemanager-omm-20250107224846-pid340890-gc.log.0.current": "yarn-gc"
    "yarn/node-group-1LqEZ0003.mrs-usp3.com_8041/container_e12_1736999506338_0001_01_000003/stdout.ext.log": "executor-2"
    "yarn/node-group-1LqEZ0002.mrs-usp3.com_8041/container_e12_1736999506338_0001_01_000002/stdout.ext.log": "executor-1"
    "yarn/node-group-1LqEZ0001.mrs-usp3.com_8041/container_e12_1736999506338_0001_01_000001/stdout.ext.log": "AppMaster"
    "console.log": "driver"
    "status.log": "status"

ParseTimestampConfig:
  IgnoreTimezoneInfo: true
  ShortestTimestampLen: 15
  TimestampSearchEndIndex: 250

MergeConfig:
  MetricsTreeEnabled: true

  WriteAliasPerBlock: true
  WriteAliasPerLine: false
  WriteTimestampPerLine: true

  #MinTimestamp: "2025-01-17T13:12:41.434816Z"
  #MaxTimestamp: "2025-01-17T13:14:12.863Z"

  BufferSizeForRead: 104857600 # 100 MB
  BufferSizeForWrite: 104857600 # 100 MB

PrintProgressConfig:
    PrintProgressEnabled: true
    InitialDelayMillis: 1000
    PeriodMillis: 1000
