carbon.indexserver.zookeeper.dir = /indexserver
carbon.disable.index.server.fallback = false
carbon.number.of.cores.while.loading = 6
carbon.sort.size = 500000
carbon.enable.index.server = false
carbon.sort.file.write.buffer.size = 16384
carbon.enable.show.mv.for.showtables = false
max.query.execution.time = 60
carbon.enable.multi.version.table.status = false
carbon.enable.droptable.remove.staleentry = true
carbon.enable.compact.autoclean = false
carbon.dataload.group.name = ficommon
carbon.private.fi = true
carbon.indexserver.HA.enabled = true
carbon.tablestatus.multi.version.file.count = 3
carbon.enable.partitiondata.trash = true
carbon.timestamp.format = yyyy-MM-dd HH:mm:ss
carbon.enable.badrecord.action.redirect = false
carbon.number.of.cores = 4
carbon.index.server.port = 22900
carbon.inmemory.record.size = 480000
