Client {
com.sun.security.auth.module.Krb5LoginModule required
useKeyTab=true
keyTab="/opt/huawei/Bigdata/FusionInsight_HD_8.6.0.1/install/FusionInsight-Hadoop-3.3.1/hadoop/keytabs/yarn/mr_zk.keytab"
principal="mr_zk/hadoop.4f051880_a5f9_f68b_9a19_27e0d0f6fe02.com"
useTicketCache=false
storeKey=true
debug=true;
};