# Set everything to be logged to the console
log4j.rootCategory=INFO, sparklog
log4j.appender.sparklog=org.apache.log4j.RollingFileAppender
log4j.appender.sparklog.File = ${spark.yarn.app.container.log.dir}/stdout
log4j.appender.sparklog.Append = true
log4j.appender.sparklog.MaxFileSize=50MB
log4j.appender.sparklog.MaxBackupIndex=10
log4j.appender.sparklog.layout = org.apache.log4j.PatternLayout
log4j.appender.sparklog.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | [%t] | %m | %c.%M(%F:%L)%n

# Settings to quiet third party logs that are too verbose
log4j.logger.org.sparkproject.jetty=WARN
log4j.logger.org.sparkproject.jetty.util.component.AbstractLifeCycle=ERROR
log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper=INFO
log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=INFO