[kdcdefaults]
kdc_ports = 172.16.175.150:21732
kdc_tcp_ports = 172.16.175.150:21732

[libdefaults]
default_realm = 4F051880_A5F9_F68B_9A19_27E0D0F6FE02.COM
kdc_timeout = 2500
clockskew = 300
use_dns_lookup = 0
udp_preference_limit = 1465
max_retries = 2
dns_lookup_kdc = false
dns_lookup_realm = false
renewable = false
forwardable = false
renew_lifetime = 0m
max_renewable_life = 30m
allow_extend_version = false
default_ccache_name = FILE:/tmp//krb5cc_%{uid}

[realms]
4F051880_A5F9_F68B_9A19_27E0D0F6FE02.COM = {
kdc = 172.16.175.150:21732
kdc = 172.16.240.143:21732
admin_server = 172.16.240.143:21730
admin_server = 172.16.175.150:21730
kpasswd_server = 172.16.240.143:21731
kpasswd_server = 172.16.175.150:21731
database_module = openldap_ldapconf
supported_enctypes = aes256-cts-hmac-sha1-96:special aes128-cts-hmac-sha1-96:special
kpasswd_port = 21731
kadmind_port = 21730
renewable = false
forwardable = false
renew_lifetime = 0m
max_renewable_life = 30m
acl_file = /opt/huawei/Bigdata/FusionInsight_BASE_8.6.0.1/install/FusionInsight-kerberos-1.21/kerberos/var/krb5kdc/kadm5.acl
dict_file = /opt/huawei/Bigdata/common/runtime0/security/weakPasswdDic/weakPasswdForKdc.ini
key_stash_file = /opt/huawei/Bigdata/FusionInsight_BASE_8.6.0.1/install/FusionInsight-kerberos-1.21/kerberos/var/krb5kdc/.k5.4F051880_A5F9_F68B_9A19_27E0D0F6FE02.COM
}

[domain_realm]
.4f051880_a5f9_f68b_9a19_27e0d0f6fe02.com = 4F051880_A5F9_F68B_9A19_27E0D0F6FE02.COM

[logging]
kdc = SYSLOG:INFO:DAEMON
admin_server = SYSLOG:INFO:DAEMON
default = SYSLOG:NOTICE:DAEMON
