log4j.appender.rangerAudit.File = ${spark.yarn.app.container.log.dir}/ranger-audit.log
log4j.logger.org.sparkproject.jetty = WARN
log4j.appender.rangerAudit.layout = org.apache.log4j.PatternLayout
log4j.appender.sparklog = org.apache.log4j.RollingFileAppender
log4j.appender.rangerAudit.MaxFileSize = 20MB
log4j.additivity.state.change.logger = false
log4j.rootCategory = INFO,sparklog
spark.executor.log.level = INFO
log4j.appender.sparklog.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | [%t] | %m | %c.%M(%F:%L)%n
log4j.appender.rangerAudit = org.wcc.framework.log.SizeRollingZipFileATimeAppender
log4j.appender.sparklog.Append = true
log4j.appender.sparklog.layout = org.apache.log4j.PatternLayout
log4j.appender.rangerAudit.MaxBackupIndex = 20
log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper = INFO
log4j.logger.org.apache.hadoop.hive.ql.metadata.multiversion.MultiVersionFactory = FATAL
log4j.appender.sparklog.MaxBackupIndex = 10
log4j.appender.sparklog.File = ${spark.yarn.app.container.log.dir}/stdout
log4j.logger.org.apache.ranger.audit.provider.AuditProviderFactory = ERROR
log4j.logger.org.sparkproject.jetty.util.component.AbstractLifeCycle = ERROR
log4j.logger.com.obs = WARN
log4j.appender.rangerAudit.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | [%t] | %m | %c.%M(%F:%L)%n
log4j.logger.xaaudit = INFO,rangerAudit
log4j.logger.org.apache.hadoop.fs.obs = WARN
log4j.logger.com.huawei.hadoop.dynalogger.DynaLog4jWatcher = OFF
log4j.appender.sparklog.MaxFileSize = 50MB
log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter = INFO
log4j.logger.org.apache.spark.deploy.security = DEBUG
log4j.logger.org.apache.hadoop.security = DEBUG
log4j.logger.org.apache.hadoop.security.SaslRpcClient = WARN
log4j.logger.org.apache.hadoop.security.UserGroupInformation = INFO
log4j.logger.org.apache.hadoop.hdfs.server.namenode.ha = INFO
log4j.logger.org.apache.hadoop.fs = DEBUG
log4j.logger.com.huaweicloud.memartscc = DEBUG
log4j.logger.DelegationTokenVerifier = DEBUG
