status = WARN
property.auditDir = /opt/client-md/Spark/spark/audit

# Root Logger
rootLogger.level = WARN
rootLogger.appenderRef.console.ref = Console

# Console Appender
appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = UsPatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | %t | %m | %c.%M(%F:%L)%n

# Console Appender Filter
appender.console.filter.regex.type = RegexFilter
appender.console.filter.regex.regex = Thrift error occurred during processing of message
appender.console.filter.regex.onMatch = DENY
appender.console.filter.regex.onMismatch = NEUTRAL

# SecurityLogger Appender
appender.securitylogger.type = RollingFile
appender.securitylogger.name = SecurityLogger
appender.securitylogger.fileName = ${auditDir}/${sys:user.name}_audit.log
appender.securitylogger.filePattern = ${auditDir}/${sys:user.name}_audit-%d{MM-dd-yyyy}-%i.log.gz
appender.securitylogger.filePermissions = rw-------
appender.securitylogger.layout.type = PatternLayout
appender.securitylogger.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | %t | %m | %c.%M(%F:%L)%n
appender.securitylogger.policies.type = Policies
appender.securitylogger.policies.time.type = TimeBasedTriggeringPolicy
appender.securitylogger.policies.time.interval = 1
appender.securitylogger.policies.time.modulate = true
appender.securitylogger.policies.size.type = SizeBasedTriggeringPolicy
appender.securitylogger.policies.size.size = 10MB
appender.securitylogger.strategy.type = DefaultRolloverStrategy
appender.securitylogger.strategy.max = 10
appender.securitylogger.strategy.action.type = PosixViewAttribute
appender.securitylogger.strategy.action.basePath = ${auditDir}
appender.securitylogger.strategy.action.IfFileName.type = IfFileName
appender.securitylogger.strategy.action.IfFileName.glob = *log.gz
appender.securitylogger.strategy.action.filePermissions = r--------


# Loggers
logger.spark-repl.name = org.apache.spark.repl.Main
logger.spark-repl.level = WARN

logger.jetty.name = org.spark_project.jetty
logger.jetty.level = WARN

logger.jetty-lifecycle.name = org.spark_project.jetty.util.component.AbstractLifeCycle
logger.jetty-lifecycle.level = ERROR

logger.spark-repl-expressiontypechecker.name = org.apache.spark.repl.SparkIMain$exprTyper
logger.spark-repl-expressiontypechecker.level = INFO

logger.spark-repl-interpreter.name = org.apache.spark.repl.SparkILoop$SparkILoopInterpreter
logger.spark-repl-interpreter.level = INFO

logger.parquet.name = org.apache.parquet
logger.parquet.level = ERROR

logger.parquet-category.name = parquet
logger.parquet-category.level = ERROR

logger.hive-metastore.name = org.apache.hadoop.hive.metastore.RetryingHMSHandler
logger.hive-metastore.level = FATAL

logger.hive-function-registry.name = org.apache.hadoop.hive.ql.exec.FunctionRegistry
logger.hive-function-registry.level = ERROR

logger.hive-multiversion.name = org.apache.hadoop.hive.ql.metadata.multiversion.MultiVersionFactory
logger.hive-multiversion.level = FATAL

logger.hive-conf.name = org.apache.hadoop.hive.conf.HiveConf
logger.hive-conf.level = ERROR

logger.ranger-config.name = org.apache.ranger.authorization.hadoop.config
logger.ranger-config.level = FATAL

logger.ranger-audit.name = org.apache.ranger.audit.provider.AuditProviderFactory
logger.ranger-audit.level = ERROR

logger.huawei-alarm.name = com.huawei.bigdata.om.agent.alarmcommon.SuppressionAlarmUtils
logger.huawei-alarm.level = FATAL

logger.securitylogger.name = SecurityLogger
logger.securitylogger.level = INFO
logger.securitylogger.additivity = false
logger.securitylogger.appenderRef.securitylogger.ref = SecurityLogger
logger.org_apache_spark_deploy_security.name = org.apache.spark.deploy.security
logger.org_apache_spark_deploy_security.level = DEBUG
logger.org_apache_hadoop_security.name = org.apache.hadoop.security
logger.org_apache_hadoop_security.level = DEBUG
logger.org_apache_hadoop_security_SaslRpcClient.name = org.apache.hadoop.security.SaslRpcClient
logger.org_apache_hadoop_security_SaslRpcClient.level = WARN
logger.org_apache_hadoop_security_UserGroupInformation.name = org.apache.hadoop.security.UserGroupInformation
logger.org_apache_hadoop_security_UserGroupInformation.level = INFO
logger.org_apache_hadoop_hdfs_server_namenode_ha.name = org.apache.hadoop.hdfs.server.namenode.ha
logger.org_apache_hadoop_hdfs_server_namenode_ha.level = INFO
logger.org_apache_hadoop_fs.name = org.apache.hadoop.fs
logger.org_apache_hadoop_fs.level = DEBUG
logger.com_huaweicloud_memartscc.name = com.huaweicloud.memartscc
logger.com_huaweicloud_memartscc.level = DEBUG
logger.DelegationTokenVerifier.name = DelegationTokenVerifier
logger.DelegationTokenVerifier.level = DEBUG
