status = warn

# Root logger
rootLogger.level = INFO
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.rolling.ref = RollingFile

# Console appender
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | [%t] | %m | %c.%M(%F:%L)%n

# RollingFile appender (原sparklog)
appender.rolling.type = RollingFile
appender.rolling.name = RollingFile
appender.rolling.fileName = ${sys:spark.yarn.app.container.log.dir}/stdout
appender.rolling.filePattern = ${sys:spark.yarn.app.container.log.dir}/stdout-%d{MM-dd-yyyy}-%i
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | [%t] | %m | %c.%M(%F:%L)%n
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 50MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 10
appender.rolling.strategy.action.type = PosixViewAttribute
appender.rolling.strategy.action.basePath = ${sys:spark.yarn.app.container.log.dir}
appender.rolling.strategy.action.IfFileName.type = IfFileName
appender.rolling.strategy.action.IfFileName.glob = stdout.ext-*
appender.rolling.strategy.action.filePermissions = r--r-----

# RangerAudit appender
appender.rangerAudit.type = RollingFile
appender.rangerAudit.name = RangerAudit
appender.rangerAudit.fileName = ${sys:spark.yarn.app.container.log.dir}/ranger-audit.log
appender.rangerAudit.filePattern = ${sys:spark.yarn.app.container.log.dir}/ranger-audit-%d{MM-dd-yyyy}-%i.log.gz
appender.rangerAudit.layout.type = PatternLayout
appender.rangerAudit.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | [%t] | %m | %c.%M(%F:%L)%n
appender.rangerAudit.policies.type = Policies
appender.rangerAudit.policies.size.type = SizeBasedTriggeringPolicy
appender.rangerAudit.policies.size.size = 20MB
appender.rangerAudit.strategy.type = DefaultRolloverStrategy
appender.rangerAudit.strategy.max = 20
appender.rangerAudit.strategy.action.type = PosixViewAttribute
appender.rangerAudit.strategy.action.basePath = ${sys:spark.yarn.app.container.log.dir}
appender.rangerAudit.strategy.action.IfFileName.type = IfFileName
appender.rangerAudit.strategy.action.IfFileName.glob = ranger-audit-*
appender.rangerAudit.strategy.action.filePermissions = r--r-----

# Loggers
logger.sparkproject_jetty.name = org.sparkproject.jetty
logger.sparkproject_jetty.level = WARN

logger.spark_repl_main.name = org.apache.spark.repl.SparkIMain$exprTyper
logger.spark_repl_main.level = INFO

logger.spark_repl_interpreter.name = org.apache.spark.repl.SparkILoop$SparkILoopInterpreter
logger.spark_repl_interpreter.level = INFO

logger.hadoop_hive.name = org.apache.hadoop.hive.ql.metadata.multiversion.MultiVersionFactory
logger.hadoop_hive.level = FATAL

logger.ranger_audit_provider.name = org.apache.ranger.audit.provider.AuditProviderFactory
logger.ranger_audit_provider.level = ERROR

logger.jetty_util.name = org.sparkproject.jetty.util.component.AbstractLifeCycle
logger.jetty_util.level = ERROR

logger.obs.name = com.obs
logger.obs.level = WARN

logger.hadoop_fs_obs.name = org.apache.hadoop.fs.obs
logger.hadoop_fs_obs.level = WARN

logger.dynalogger.name = com.huawei.hadoop.dynalogger.DynaLog4jWatcher
logger.dynalogger.level = OFF

logger.xaaudit.name = xaaudit
logger.xaaudit.level = INFO
logger.xaaudit.appenderRef.rangerAudit.ref = RangerAudit
logger.xaaudit.additivity = false

# Spark executor log level
property.spark.executor.log.level = INFO
logger.org_apache_spark_deploy_security.name = org.apache.spark.deploy.security
logger.org_apache_spark_deploy_security.level = DEBUG
logger.org_apache_hadoop_security.name = org.apache.hadoop.security
logger.org_apache_hadoop_security.level = DEBUG
logger.org_apache_hadoop_security_SaslRpcClient.name = org.apache.hadoop.security.SaslRpcClient
logger.org_apache_hadoop_security_SaslRpcClient.level = WARN
logger.org_apache_hadoop_security_UserGroupInformation.name = org.apache.hadoop.security.UserGroupInformation
logger.org_apache_hadoop_security_UserGroupInformation.level = INFO
logger.org_apache_hadoop_hdfs_server_namenode_ha.name = org.apache.hadoop.hdfs.server.namenode.ha
logger.org_apache_hadoop_hdfs_server_namenode_ha.level = INFO
logger.org_apache_hadoop_fs.name = org.apache.hadoop.fs
logger.org_apache_hadoop_fs.level = DEBUG
logger.com_huaweicloud_memartscc.name = com.huaweicloud.memartscc
logger.com_huaweicloud_memartscc.level = DEBUG
logger.DelegationTokenVerifier.name = DelegationTokenVerifier
logger.DelegationTokenVerifier.level = DEBUG
