#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Set everything to be logged to the console
log4j.rootCategory=WARN, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.err
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | %t | %m | %c.%M(%F:%L)%n

# Set the default spark-shell log level to WARN. When running the spark-shell, the
# log level for this class is used to overwrite the root logger's log level, so that
# the user can have different defaults for the shell and regular Spark apps.
log4j.logger.org.apache.spark.repl.Main=WARN

# Settings to quiet third party logs that are too verbose
log4j.logger.org.spark_project.jetty=WARN
log4j.logger.org.spark_project.jetty.util.component.AbstractLifeCycle=ERROR
log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper=INFO
log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=INFO
log4j.logger.org.apache.parquet=ERROR
log4j.logger.parquet=ERROR

# SPARK-9183: Settings to avoid annoying messages when looking up nonexistent UDFs in SparkSQL with Hive support
log4j.logger.org.apache.hadoop.hive.metastore.RetryingHMSHandler=FATAL
log4j.logger.org.apache.hadoop.hive.ql.exec.FunctionRegistry=ERROR
log4j.appender.SQLDefense.File = /opt/client-md/Spark/spark/audit/query.log
log4j.appender.auditlog.File = /opt/client-md/Spark/spark/audit/${user.name}_audit.log
log4j.additivity.SQLDefense=false
log4j.appender.SQLDefense.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | %t | %m | %c.%M(%F:%L)%n
log4j.appender.SQLDefense.layout = org.apache.log4j.PatternLayout
log4j.appender.SQLDefense.MaxBackupIndex = 10
log4j.appender.SQLDefense.MaxFileSize = 10MB
log4j.logger.SQLDefense = INFO,SQLDefense
log4j.appender.SQLDefense = com.huawei.spark.utils.SizeRollingZipFileATime4AuditAppender
log4j.logger.org.apache.hadoop.hive.ql.metadata.multiversion.MultiVersionFactory=FATAL
log4j.additivity.SecurityLogger=false
log4j.appender.auditlog.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss,SSS} | %-5p | %t | %m | %c.%M(%F:%L)%n
log4j.appender.auditlog.layout = org.apache.log4j.PatternLayout
log4j.appender.auditlog.MaxBackupIndex = 10
log4j.appender.auditlog.MaxFileSize = 10MB
log4j.logger.SecurityLogger = INFO,auditlog
log4j.appender.auditlog = com.huawei.spark.utils.SizeRollingZipFileATime4AuditAppender
log4j.logger.org.apache.hadoop.hive.conf.HiveConf=ERROR
log4j.logger.org.apache.ranger.authorization.hadoop.config=FATAL
log4j.logger.org.apache.ranger.audit.provider.AuditProviderFactory=ERROR
log4j.logger.com.huawei.bigdata.om.agent.alarmcommon.SuppressionAlarmUtils=FATAL

# For deploying Spark ThriftServer
# SPARK-34128：Suppress undesirable TTransportException warnings involved in THRIFT-4805
log4j.appender.console.filter.1=org.apache.log4j.varia.StringMatchFilter
log4j.appender.console.filter.1.StringToMatch=Thrift error occurred during processing of message
log4j.appender.console.filter.1.AcceptOnMatch=false
log4j.logger.org.apache.spark.deploy.security = DEBUG
log4j.logger.org.apache.hadoop.security = DEBUG
log4j.logger.org.apache.hadoop.security.SaslRpcClient = WARN
log4j.logger.org.apache.hadoop.security.UserGroupInformation = INFO
log4j.logger.org.apache.hadoop.hdfs.server.namenode.ha = INFO
log4j.logger.org.apache.hadoop.fs = DEBUG
log4j.logger.com.huaweicloud.memartscc = DEBUG
log4j.logger.DelegationTokenVerifier = DEBUG
